/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',          // La clase 'dark' en <html> activa el modo oscuro
    content: ["./*.{html,js}"],
    theme: {
        extend: {
            // TODOS los colores ahora toman su valor de variables CSS
            colors: {
                'surface-tint': 'var(--color-surface-tint)',
                'surface-variant': 'var(--color-surface-variant)',
                'surface-container-low': 'var(--color-surface-container-low)',
                'on-error-container': 'var(--color-on-error-container)',
                'on-primary-container': 'var(--color-on-primary-container)',
                'inverse-primary': 'var(--color-inverse-primary)',
                'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
                'surface-bright': 'var(--color-surface-bright)',
                'surface-container-lowest': 'var(--color-surface-container-lowest)',
                'secondary-fixed': 'var(--color-secondary-fixed)',
                'surface-container': 'var(--color-surface-container)',
                'on-primary-fixed': 'var(--color-on-primary-fixed)',
                'on-surface-variant': 'var(--color-on-surface-variant)',
                'outline': 'var(--color-outline)',
                'surface-container-high': 'var(--color-surface-container-high)',
                'error-container': 'var(--color-error-container)',
                'secondary-container': 'var(--color-secondary-container)',
                'on-tertiary': 'var(--color-on-tertiary)',
                'inverse-on-surface': 'var(--color-inverse-on-surface)',
                'primary': 'var(--color-primary)',
                'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
                'primary-fixed': 'var(--color-primary-fixed)',
                'surface-dim': 'var(--color-surface-dim)',
                'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
                'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
                'tertiary-container': 'var(--color-tertiary-container)',
                'tertiary': 'var(--color-tertiary)',
                'on-error': 'var(--color-on-error)',
                'on-surface': 'var(--color-on-surface)',
                'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
                'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
                'surface': 'var(--color-surface)',
                'outline-variant': 'var(--color-outline-variant)',
                'on-secondary': 'var(--color-on-secondary)',
                'primary-container': 'var(--color-primary-container)',
                'tertiary-fixed': 'var(--color-tertiary-fixed)',
                'on-tertiary-container': 'var(--color-on-tertiary-container)',
                'on-secondary-container': 'var(--color-on-secondary-container)',
                'on-primary': 'var(--color-on-primary)',
                'surface-container-highest': 'var(--color-surface-container-highest)',
                'inverse-surface': 'var(--color-inverse-surface)',
                'error': 'var(--color-error)',
                'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
                'secondary': 'var(--color-secondary)',
                'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
                'background': 'var(--color-background)',
                'on-background': 'var(--color-on-background)',
                'accent': 'var(--color-accent)',           // lo usas en algunos gradientes
                'white-alpha-10': 'var(--color-white-alpha-10)',
            },
            spacing: {
                margin_mobile: '16px',
                container_max_width: '1200px',
                unit: '8px',
                sidebar_width: '280px',
                margin_desktop: '48px',
                gutter: '24px',
            },
            fontFamily: {
                'headline-md': ['Inter', 'sans-serif'],
                'headline-lg': ['Inter', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'headline-lg-mobile': ['Inter', 'sans-serif'],
                'label-sm': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'code': ['monospace'],
            },
            fontSize: {
                'headline-md': ['24px', {lineHeight: '1.3', fontWeight: '600'}],
                'headline-lg': ['32px', {lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700'}],
                'body-lg': ['18px', {lineHeight: '1.6', fontWeight: '400'}],
                'headline-lg-mobile': ['24px', {lineHeight: '1.2', fontWeight: '700'}],
                'label-sm': ['14px', {lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600'}],
                'body-md': ['16px', {lineHeight: '1.6', fontWeight: '400'}],
                'code': ['14px', {lineHeight: '1.5', fontWeight: '400'}],
            },
        },
    },
    plugins: [],
};